<<<<<<< HEAD
magnetic_decliation_radians: 0
yaw_offset: 0
zero_altitude: true

broadcast_cartesian_transform: false
publish_filtered_gps: false

use_odometry_yaw: false
wait_for_datum: false
=======
# Frequency of the main run loop
frequency: 30

# IMU yaw should report 0 when facing east
yaw_offset: 0

# Whether or not to set the altitude to 0 in the output odom message
zero_altitude: true

# Whether the transform world_frame->utm transform is broadcast
broadcast_cartesian_transform: false
broadcast_cartesian_transform_as_parent_frame: false

# If this is true, all received odometry data is converted back to a lat/lon
# and published as a NavSatFix message as /gps/filtered.
publish_filtered_gps: true

# If this is true, the node ignores the IMU data and gets its heading from the
# odometry source (typically the /odometry/filtered topic coming from one of
# robot_localization's state estimation nodes). BE CAREFUL when using this! The
# yaw value in your odometry source *must* be world-referenced, e.g., you cannot
# use your odometry source for yaw if your yaw data is based purely on integrated
# velocities. Defaults to false.
use_odometry_yaw: false

# If true, will retrieve the datum from the 'datum' parameter below, if
# available. If no 'datum' parameter exists, navsat_transform_node will
# wait until the user calls the 'datum' service with the SetDatum service message.
wait_for_datum: false
>>>>>>> main
