TrajectoryPlannerROS:
  # Velocities
  max_vel_x: 3.0
  min_vel_x: 0.1
  max_vel_theta: 2.0
  min_in_place_vel_theta: 1.0

  # Acceleratiions
  acc_lim_x: 0.8
  acc_lim_theta: 0.5

  # Trajectory Scoring
  pdist_scale: 2.5
  gdist_scale: 0.8
  
  # Forward Simulation
  sim_time: 1.5



  holonomic_robot: false

