name: Continuous Integration

on: [pull_request]

jobs:
  catkin_build:
    name: Build workspace
    runs-on: ubuntu-20.04
    container: ros:noetic
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: catkin build
