name: Continuous Integration

on: [pull_request]

jobs:
  catkin_build:
    name: Build workspace
    runs-on: ubuntu-20.04
    container: ros:noetic
    steps:
      - run: sudo apt update && sudo apt install git
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.CI_SSH_PRIVATE }}
          submodules: recursive
      - run: catkin build
