TrajectoryPlannerROS:
  # Velocities
  max_vel_x: 1.0
  min_vel_x: 0.1
  max_vel_theta: 0.8
  min_in_place_vel_theta: 3.0

  # Acceleratiions
  acc_lim_x: 0.8
  acc_lim_theta: 0.5

  # Trajectory Scoring
  path_distance_bias: 32
  goal_distance_bias: 20
  occdist scale: 0.02
  
  # Forward Simulation
  vx_sample: 20
  vth_sample: 40
  controller_frequency: 1

  # Goal Tolerance
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.3

  holonomic_robot: false

