obstacle_range: 2.5
raytrace_range: 3.0
# Modify with actual dimensions of the robot
footprint: [[-0.325, -0.25], [-0.325, 0.25], [0.325, 0.25], [0.325, -0.25]]
# footprint_padding: 0.05
inflation_radius: 1.0
# cost scaling factor: 2.5
transform_tolerance: 0.5

observation_sources: laser_scan_sensor 
laser_scan_sensor: {sensor_frame: lidar, 
                    data_type: LaserScan, 
                    topic: /lidar/ground_truth, 
                    marking: true, 
                    clearing: true}
                    