local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  # static_map: true
  rolling_window: true
  width: 2.3
  height: 2.3
  resolution: 0.098039216
